[program:lms]
command=/home/lms/project/venv/bin/gunicorn --workers 3 --bind 127.0.0.1:8000 lms_project.wsgi:application
directory=/home/lms/project
user=lms
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/lms-gunicorn.log
stderr_logfile=/var/log/lms-gunicorn-error.log