# Generated by Django 6.0.7 on 2026-07-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Даты обновления'),
        ),
    ]
